name: ParlaClans
main: com.rdev.ParlaClans
version: 1.14
api-version: 1.13
author: RDev_
description: >
  ParlaClans Plugin
commands:
  ParlaClans:
    aliases: [clans, clan]
    description: ParlaClans command